repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v16.0.6
    hooks:
      - id: clang-format
        types: [c]
        args: [--style=file]
      - id: clang-format
        types: [header]
        args: [--style=file]

  - repo: https://github.com/pre-commit/mirrors-clang-tidy
    rev: v16.0.6
    hooks:
      - id: clang-tidy
        types: [c]
        args: [--fix, --config-file=.clang-tidy]
      - id: clang-tidy
        types: [header]
        args: [--fix, --config-file=.clang-tidy]

  - repo: https://github.com/danmar/cppcheck
    rev: v2.12.0
    hooks:
      - id: cppcheck
        args: [--enable=all, --inconclusive, --suppress=missingInclude]

  - repo: local
    hooks:
      - id: check-makefile
        name: Check Makefile syntax
        entry: make -n --dry-run all
        language: system
        pass_filenames: false
        always_run: true